vault

diff --git a/bin/deploy_dlna-permissions b/bin/deploy_dlna-permissions
--- a/bin/deploy_dlna-permissions
+++ b/bin/deploy_dlna-permissions
@@ -2,15 +2,15 @@
 
 # READY
 
-zfs list priv/data || zfs create priv/data
-if ! zfs list priv/data > /dev/null ; then
-    echo "ERROR: missing priv/data"
+zfs list vault/data || zfs create vault/data
+if ! zfs list vault/data > /dev/null ; then
+    echo "ERROR: missing vault/data"
     exit 1
 fi
 
-install -d -m 755 /priv/data/movies
-install -d -m 755 /priv/data/music
-install -d -m 755 /priv/data/photos
+install -d -m 755 /vault/data/movies
+install -d -m 755 /vault/data/music
+install -d -m 755 /vault/data/photos
 
 crontabbed
 if sysctl security.jail.jailed | grep 1 >/dev/null 2>&1; then
