expect HTTP_PROXY

diff --git a/bin/deploy_gitlab_src b/bin/deploy_gitlab_src
--- a/bin/deploy_gitlab_src
+++ b/bin/deploy_gitlab_src
@@ -5,7 +5,7 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150624-170655
+SCRIPTVERSION=150624-183925
 
 if [ "x" == "x${GITLABSRC}" ]; then
     GITLABSRC=https://gitlab.com/
@@ -59,6 +59,11 @@ pkg install -y sudo bash icu cmake pkgconf git nginx ruby ruby21-gems logrotate 
 
 if [ ! -e /usr/local/bin/createuser ]; then
     echo "ERROR: install failed"
+    exit 1
+fi
+
+if [ "x" == "x${HTTP_PROXY}" ]; then
+    echo "ERROR: expecting HTTP_PROXY"
     exit 1
 fi
 
