test that tank/vmrc is mounted

diff --git a/bin/deploy_pfsense b/bin/deploy_pfsense
--- a/bin/deploy_pfsense
+++ b/bin/deploy_pfsense
@@ -5,10 +5,15 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150709-032330
+SCRIPTVERSION=150822-043613
 
 if sysctl security.jail.jailed | grep 1 >/dev/null 2>&1; then
     echo "ERROR: Cannot run in a jail"
+    exit 1
+fi
+
+if ! zfs list tank/vmrc ; then
+    echo "ERROR: tank/vmrc is not mounted."
     exit 1
 fi
 
