look for SQUIDPKG env var

diff --git a/bin/deploy_squid b/bin/deploy_squid
--- a/bin/deploy_squid
+++ b/bin/deploy_squid
@@ -2,7 +2,10 @@
 
 # READY
 
-SQUIDPKG=/var/ports/packages/All/squid-3.5.10.txz
+if [ "x" == "x${SQUIDPKG}" ]; then
+    echo "ERROR: SQUIDPKG not defined."
+    exit 1
+fi
 
 export BATCH=yes
 
