naive test if pkg succeeded

diff --git a/bin/deploy_baikal b/bin/deploy_baikal
--- a/bin/deploy_baikal
+++ b/bin/deploy_baikal
@@ -6,7 +6,7 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150616-030316
+SCRIPTVERSION=150618-013505
 
 if [ "x" == "x${FQDN}" ]; then
     echo "Please set or export variable FQDN"
@@ -16,6 +16,11 @@ fi
 pkg install -y baikal \
 lang/php56 \
 nginx
+
+if [ ! -e /usr/local/www/baikal/Specific ]; then
+    echo "ERROR: install failed"
+    exit 1
+fi
 
 nginx-config-sites-enabled
 cat /usr/local/etc/nginx/sites-available/example-baikal | sed "s/localhost.my.domain/${FQDN}/" >/usr/local/etc/nginx/sites-enabled/baikal
diff --git a/bin/deploy_couchdb b/bin/deploy_couchdb
--- a/bin/deploy_couchdb
+++ b/bin/deploy_couchdb
@@ -5,7 +5,7 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150616-030130
+SCRIPTVERSION=150618-013505
 
 if [ "x" == "x${FQDN}" ]; then
     echo "Please set or export variable FQDN" 2>&1
@@ -13,6 +13,11 @@ if [ "x" == "x${FQDN}" ]; then
 fi
 
 pkg install -y couchdb nginx
+
+if [ ! -e /usr/local/etc/rc.d/couchdb ]; then
+    echo "ERROR: install failed"
+    exit 1
+fi
 
 nginx-config-sites-enabled
 cat /usr/local/etc/nginx/sites-available/example-couchdb | sed "s/localhost.my.domain/${FQDN}/" >/usr/local/etc/nginx/sites-enabled/dtfc
diff --git a/bin/deploy_couchdbdtfc b/bin/deploy_couchdbdtfc
--- a/bin/deploy_couchdbdtfc
+++ b/bin/deploy_couchdbdtfc
@@ -5,7 +5,7 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150610-062711
+SCRIPTVERSION=150618-013505
 
 if [ "x" == "x${FQDN}" ]; then
     echo "Please set or export variable FQDN" 2>&1
@@ -15,6 +15,11 @@ fi
 MYUSER="dtfc"
 
 pkg install -y lang/go nginx sudo couchdb
+
+if [ ! -e /usr/local/etc/rc.d/couchdb ]; then
+    echo "ERROR: install failed"
+    exit 1
+fi
 
 echo "${MYUSER}:1004::::::/usr/home/${MYUSER}:/bin/sh:" | adduser -w no -f -
 
diff --git a/bin/deploy_ejabberd b/bin/deploy_ejabberd
--- a/bin/deploy_ejabberd
+++ b/bin/deploy_ejabberd
@@ -5,12 +5,18 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150617-071308
+SCRIPTVERSION=150618-013505
 
 ROOTUSER="root"
 ROOTPASS="password"
 
 pkg install -y net-im/ejabberd
+
+if [ ! -e /usr/local/etc/ejabberd/ejabberd.yml.example ]; then
+    echo "ERROR: install failed"
+    exit 1
+fi
+
 
 if [ ! -f /usr/local/etc/ejabberd/ejabberd.yml ]; then
     if [ -f /usr/local/etc/ejabberd/ejabberd.yml.example ]; then
diff --git a/bin/deploy_gitlab_src b/bin/deploy_gitlab_src
--- a/bin/deploy_gitlab_src
+++ b/bin/deploy_gitlab_src
@@ -5,12 +5,13 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150617-071308
+SCRIPTVERSION=150618-013505
 
 DB="gitlabhq_production"
 DBUSER="git"
 DBPASS="password"
 ROOTPASS="password"
+BRANCH="7-7-stable"
 
 # Based on https://www.b1c1l1.com/blog/2011/05/09/using-utf-8-unicode-on-freebsd/
 # and https://github.com/gitlabhq/gitlab-recipes/blob/master/install/freebsd/freebsd-10.md
@@ -41,6 +42,12 @@ fi
 
 # 2 Dependencies
 pkg install -y sudo bash icu cmake pkgconf git nginx ruby ruby21-gems logrotate redis postgresql94-server postfix krb5
+
+if [ ! -e /usr/local/pgsql/data/pg_hba.conf ]; then
+    echo "ERROR: install failed"
+    exit 1
+fi
+
 gem install bundler --no-ri --no-rdoc
 
 if sysctl security.jail.jailed | grep 0 >/dev/null ; then
@@ -101,7 +108,7 @@ service redis start
 
 # 6 gitlab
 cd /usr/home/git
-sudo -u git -H git clone https://gitlab.com/gitlab-org/gitlab-ce.git -b 7-7-stable gitlab
+sudo -u git -H git clone https://gitlab.com/gitlab-org/gitlab-ce.git -b ${BRANCH} gitlab
 cd /usr/home/git/gitlab
 sudo -u git -H cp config/gitlab.yml.example config/gitlab.yml
 #The option host: should be set to your domain, e.g. "gitlab.mysite.com".
diff --git a/bin/deploy_hordewebmail b/bin/deploy_hordewebmail
--- a/bin/deploy_hordewebmail
+++ b/bin/deploy_hordewebmail
@@ -6,7 +6,7 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150617-071308
+SCRIPTVERSION=150618-013505
 
 DB="horde"
 DBUSER="horde"
@@ -39,6 +39,10 @@ pecl-pam \
 postgresql93-server \
 apache24
 
+if [ ! -e /usr/local/www/horde/config/conf.php.dist ]; then
+    echo "ERROR: install failed"
+    exit 1
+fi
 
 apache-config-freebsd
 pkg install -fy www/mod_php56
diff --git a/bin/deploy_murmur b/bin/deploy_murmur
--- a/bin/deploy_murmur
+++ b/bin/deploy_murmur
@@ -5,9 +5,14 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150615-212959
+SCRIPTVERSION=150618-013505
 
 pkg install -y audio/murmur
+
+if [ ! -e /usr/local/etc/rc.d/murmur ]; then
+    echo "ERROR: install failed"
+    exit 1
+fi
 
 sysrc murmur_enable="YES"
 
diff --git a/bin/deploy_nginx b/bin/deploy_nginx
--- a/bin/deploy_nginx
+++ b/bin/deploy_nginx
@@ -5,9 +5,14 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150608-064125
+SCRIPTVERSION=150618-013505
 
 pkg install -y nginx
+
+if [ ! -e /usr/local/etc/nginx/nginx.conf-dist ]; then
+    echo "ERROR: install failed"
+    exit 1
+fi
 
 nginx-config-sites-enabled
 
diff --git a/bin/deploy_owncloud b/bin/deploy_owncloud
--- a/bin/deploy_owncloud
+++ b/bin/deploy_owncloud
@@ -5,7 +5,7 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150617-071308
+SCRIPTVERSION=150618-013505
 
 DB="owncloud"
 DBUSER="owncloud"
@@ -30,6 +30,11 @@ php56-pdo_pgsql \
 php56-pgsql \
 postgresql93-server \
 apache24
+
+if [ ! -e /usr/local/pgsql/data/pg_hba.conf ]; then
+    echo "ERROR: install failed"
+    exit 1
+fi
 
 apache-config-freebsd
 pkg install -fy www/mod_php56
diff --git a/bin/deploy_vnc b/bin/deploy_vnc
--- a/bin/deploy_vnc
+++ b/bin/deploy_vnc
@@ -5,7 +5,7 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150616-224131
+SCRIPTVERSION=150618-013505
 
 pkg install -y x11/xorg x11-wm/xfce4-wm \
 Thunar xfce4-tumbler \
@@ -13,6 +13,11 @@ www/epiphany \
 net/tightvnc
 #x11-wm/openbox
 #www/midori
+
+if [ ! -e /usr/local/bin/vncserver ]; then
+    echo "ERROR: install failed"
+    exit 1
+fi
 
 mkdir ~/.vnc
 
