force squid install and test if NEWINSTALL

diff --git a/bin/deploy_squid b/bin/deploy_squid
--- a/bin/deploy_squid
+++ b/bin/deploy_squid
@@ -5,32 +5,38 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150619-134746
+SCRIPTVERSION=150620-221403
 
-if [ -e /var/ports/packages/All/squid-3.5.5.txz ]; then
-    pkg add /var/ports/packages/All/squid-3.5.5.txz
-else
-    # install squid and dependencies
-    pkg install -y www/squid
-    # remove squid because we want custom options
-    pkg remove -y www/squid
-    # use portsnap
-    psnap
-
-    # we want LAX_HTTP=on
-    if [ ! -e /usr/ports/www/squid/Makefile.orig ]; then
-        cp /usr/ports/www/squid/Makefile /usr/ports/www/squid/Makefile.orig
-    fi
-    cat /usr/ports/www/squid/Makefile.orig | sed 's;OPTIONS_DEFAULT=;OPTIONS_DEFAULT=LAX_HTTP ;' >/usr/ports/www/squid/Makefile
-
-    cd /usr/ports/www/squid
-    make && make install && make package && make clean
-    # /var/ports/packages/All/squid-3.5.5.txz
+if ! sysrc squid_enable | grep YES >/dev/null ; then
+    NEWINSTALL="YES"
 fi
 
-if ! which squid ; then
-    echo "Failed to build squid."
-    exit 1
+if [ "xYES" == "x${NEWINSTALL}" ]; then
+    if [ -e /var/ports/packages/All/squid-3.5.5.txz ]; then
+        pkg add -f /var/ports/packages/All/squid-3.5.5.txz
+    else
+        # install squid and dependencies
+        pkg install -y www/squid
+        # remove squid because we want custom options
+        pkg remove -y www/squid
+        # use portsnap
+        psnap
+
+        # we want LAX_HTTP=on
+        if [ ! -e /usr/ports/www/squid/Makefile.orig ]; then
+            cp /usr/ports/www/squid/Makefile /usr/ports/www/squid/Makefile.orig
+        fi
+        cat /usr/ports/www/squid/Makefile.orig | sed 's;OPTIONS_DEFAULT=;OPTIONS_DEFAULT=LAX_HTTP ;' >/usr/ports/www/squid/Makefile
+
+        cd /usr/ports/www/squid
+        make && make install && make package && make clean
+        # /var/ports/packages/All/squid-3.5.5.txz
+    fi
+
+    if ! which squid ; then
+        echo "Failed to build squid."
+        exit 1
+    fi
 fi
 
 # Thanks to @tomster via https://github.com/freebsd/pkg/issues/1181
@@ -97,9 +103,11 @@ EOF
 
 sysrc squid_enable="YES"
 
-squid -z
+if [ "xYES" == "x${NEWINSTALL}" ]; then
+    squid -z
 
-service squid start
+    service squid start
+fi
 
 echo
 JAILIP=`ifconfig | grep inet | awk '{print $2}'`
