test if name and nicip are blank

diff --git a/bin/deploy_blank_jail b/bin/deploy_blank_jail
--- a/bin/deploy_blank_jail
+++ b/bin/deploy_blank_jail
@@ -5,12 +5,22 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150724-225557
+SCRIPTVERSION=150724-232127
 
 # Usage: env SQUID=10.7.7.1:3128 $0 name "lo1|10.7.7.253"
 
 name="$1"
 nicip="$2"
+
+if [ "x" == "x${name}" ]; then
+    echo "ERROR: name not specified"
+    exit 1
+fi
+
+if [ "x" == "x${nicip}" ]; then
+    echo "ERROR: nicip not specified"
+    exit 1
+fi
 
 if sysctl security.jail.jailed | grep 1 >/dev/null 2>&1; then
     echo "ERROR: Cannot run in a jail"
