patch vnc

diff --git a/bin/deploy_vnc b/bin/deploy_vnc
--- a/bin/deploy_vnc
+++ b/bin/deploy_vnc
@@ -5,7 +5,7 @@
 ######################################################################
 # Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
 ######################################################################
-SCRIPTVERSION=150616-033943
+SCRIPTVERSION=150616-041238
 
 pkg install -y x11/xorg x11-wm/openbox net/tightvnc
 
@@ -14,7 +14,7 @@ mkdir ~/.vnc
 if [ ! -f ~/.vnc/xstartup ]; then
     cat >~/.vnc/xstartup <<EOF
 #!/bin/sh
-xrdb $HOME/.Xresources &
+xrdb \$HOME/.Xresources &
 openbox &
 xterm -bg black -fg gray &
 EOF
@@ -28,6 +28,7 @@ cat >/usr/local/etc/rc.d/vnc <<EOF
 # REQUIRE: FILESYSTEMS LOGIN NETWORKING
 . /etc/rc.subr
 
+name="vnc"
 start_cmd="my_start"
 stop_cmd="my_stop"
 my_start()
@@ -38,7 +39,7 @@ my_stop()
 {
     # TODO need a more elegant solution than loop to kill
     local LOOP=1
-    while [ $LOOP -eq 1 ]; do
+    while [ \$LOOP -eq 1 ]; do
         if  /bin/pgrep -lf vncserver > /dev/null 2> /dev/null ; then
             /bin/pkill -lf vncserver > /dev/null 2> /dev/null
         else
@@ -47,10 +48,38 @@ my_stop()
         sleep 1
     done
 }
-load_rc_config $name
-run_rc_command "$1"
+load_rc_config \$name
+run_rc_command "\$1"
 EOF
+
+cat >/tmp/vncserver.patch <<EOF
+--- vncserver   2013-10-09 16:10:25.000000000 +0000
++++ vncserver.new       2013-10-09 16:12:45.000000000 +0000
+@@ -296,7 +296,7 @@ sub CheckDisplayNumber
+
+     socket(S, \$AF_INET, \$SOCK_STREAM, 0) || die "\$prog: socket failed: \$!\n";
+     eval 'setsockopt(S, &SOL_SOCKET, &SO_REUSEADDR, pack("l", 1))';
+-    unless (bind(S, pack('S n x12', \$AF_INET, 6000 + \$n))) {
++    unless (bind(S, sockaddr_in(6000 + \$n, &INADDR_ANY))) {
+        close(S);
+        return 0;
+     }
+@@ -304,7 +304,7 @@ sub CheckDisplayNumber
+
+     socket(S, \$AF_INET, \$SOCK_STREAM, 0) || die "\$prog: socket failed: \$!\n";
+     eval 'setsockopt(S, &SOL_SOCKET, &SO_REUSEADDR, pack("l", 1))';
+-    unless (bind(S, pack('S n x12', \$AF_INET, 5900 + \$n))) {
++    unless (bind(S, sockaddr_in(5900 + \$n, &INADDR_ANY))) {
+        close(S);
+        return 0;
+     }
+EOF
+
+cd /usr/local/bin
+patch < /tmp/vncserver.patch
+
+vncserver -depth 24 -geometry 1280x800 -nolisten tcp :1
 
 echo
 JAILIP=`ifconfig | grep inet | awk '{print $2}'`
-echo "Connect with ssh -v -N -L 5901:${JAILIP}:5901 you@your-server-ip"
+echo "Connect with ssh -L 5901:${JAILIP}:5901 you@your-server-ip"
