test for tank

diff --git a/bin/deploy_pfsense b/bin/deploy_pfsense
--- a/bin/deploy_pfsense
+++ b/bin/deploy_pfsense
@@ -1,19 +1,14 @@
 #!/bin/sh
 
-# TODO
-
-######################################################################
-# Script version is yymmdd-HHMMSS in UTC, date -u +%y%m%d-%H%M%S
-######################################################################
-SCRIPTVERSION=150822-043613
+# READY
 
 if sysctl security.jail.jailed | grep 1 >/dev/null 2>&1; then
     echo "ERROR: Cannot run in a jail"
     exit 1
 fi
 
-if ! zfs list tank/vmrc ; then
-    echo "ERROR: tank/vmrc is not mounted."
+if ! zfs list tank ; then
+    echo "ERROR: tank is not mounted."
     exit 1
 fi
 
